sudo: required
language: python
python:
    - "2.7"

os:
  - linux

#install:
#  - pip install -r requirements.txt

deploy:
    -  provider: elasticbeanstalk
       access_key_id: $AWS_ACCESS_KEY_ID_DEV
       secret_access_key:
         secure: "$AWS_SECERT_ACCESS_KEY_DEV"
       region: "ap-southeast-2"  
       app: "psh-eb-app"
       env: "psh-dev-app"
       bucket_name: "psh-s3-dev/source"
       on:
         branch: development


after_deploy:
  - echo "done deploying"