language: python
python:
  - "2.7"
cache: pip

install:
  - pip install -r requirements.txt

script: 

  - pytest


deploy:
    -  provider: elasticbeanstalk 
       access_key_id: $AWS_ACCESS_KEY_ID_DEV
       secret_access_key:
         secure: "$AWS_SECERT_ACCESS_KEY_DEV"
       region: "ap-southeast-2"  
       #app: "psh-eb-app"
       app: "psh-app"
       #env: "psh-dev-app"
       env: "psh-dev"
       bucket_name: "psh-s3-dev"
       upload-dir: source
       skip_cleanup: false
       on:
         branch: development
    -  provider: elasticbeanstalk
       access_key_id: $AWS_ACCESS_KEY_ID_PROD
       secret_access_key:
         secure: "$AWS_SECERT_ACCESS_KEY_PROD"
       region: "ap-southeast-2"  
       app: "psh-eb-app"
       env: "psh-prod-app"
       bucket_name: "psh-s3-prod"
       upload-dir: source
       skip_cleanup: true
       on:
         branch: master
    -  provider: elasticbeanstalk
       access_key_id: $AWS_ACCESS_KEY_ID_TEST
       secret_access_key:
         secure: "$AWS_SECERT_ACCESS_KEY_TEST"
       region: "ap-southeast-2"  
       app: "psh-eb-app"
       env: "psh-test-app"
       bucket_name: "psh-s3-test"
       upload-dir: source
       skip_cleanup: false
       on:
         branch: test


notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always