deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID_PROD
    secret_access_key:
      secure: "$AWS_SECERT_ACCESS_KEY_PROD"
    region: "ap-southeast-2"  
    app: "psh-eb-app"
    env: "psh-prod-app"
    bucket_name: "psh-s3-prod/source"
    on:
      branch: master

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID_TEST
    secret_access_key:
      secure: "$AWS_SECERT_ACCESS_KEY_TEST"
    region: "ap-southeast-2"  
    app: "psh-eb-app"
    env: "psh-test-app"
    bucket_name: "psh-s3-test/source"
    on:
      branch: test

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID_DEV
    secret_access_key:
      secure: "$AWS_SECERT_ACCESS_KEY_DEV"
    region: "ap-southeast-2"  
    app: "psh-eb-app"
    env: "psh-dev-app"
    bucket_name: "psh-s3-dev/source"
    on:
      branch: development
